"""ISSUE #3: migraciones modelos SQLAlchemy

Revision ID: 8ed0253e2d6d
Revises: 
Create Date: 2026-06-11 15:36:28.906304
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ed0253e2d6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analisis')
    op.drop_table('ubicaciones')
    op.drop_table('procesamiento_ia')
    op.drop_index('correo', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('modelo_dataset')
    op.drop_table('datasets')
    op.drop_table('notificaciones')
    op.drop_table('zonas_ambientales')
    op.drop_table('roles')
    op.drop_table('liquenpedia')
    op.drop_table('sesiones')
    op.drop_table('especies_liquenes')
    op.drop_table('modelos_ia')
    op.drop_table('historial_actividad')
    op.drop_table('reportes')
    op.drop_table('imagenes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenes',
    sa.Column('id_imagen', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_analisis', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nombre_imagen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ruta_imagen', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('formato_imagen', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tamano_archivo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resolucion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_subida', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('imagen_original', mysql.LONGBLOB(), nullable=True),
    sa.Column('imagen_procesada', mysql.LONGBLOB(), nullable=True),
    sa.Column('estado_imagen', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_captura', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_analisis'], ['analisis.id_analisis'], name='imagenes_ibfk_1'),
    sa.PrimaryKeyConstraint('id_imagen'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reportes',
    sa.Column('id_reporte', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('tipo_reporte', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('formato_reporte', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado_reporte', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_generacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='reportes_ibfk_1'),
    sa.PrimaryKeyConstraint('id_reporte'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historial_actividad',
    sa.Column('id_historial', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('accion_realizada', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('descripcion_accion', mysql.TEXT(), nullable=True),
    sa.Column('dispositivo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ip_usuario', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='historial_actividad_ibfk_1'),
    sa.PrimaryKeyConstraint('id_historial'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('modelos_ia',
    sa.Column('id_modelo', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_modelo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('version', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_modelo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precision_modelo', mysql.FLOAT(), nullable=True),
    sa.Column('dataset_utilizado', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_entrenamiento', sa.DATE(), nullable=True),
    sa.Column('fecha_actualizacion', mysql.TIMESTAMP(), nullable=True),
    sa.Column('estado_modelo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id_modelo'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('especies_liquenes',
    sa.Column('id_especie', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_cientifico', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('nombre_comun', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('color_predominante', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_crecimiento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('nivel_tolerancia_contaminacion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('indicador_calidad_aire', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('habitat', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('imagen_referencia', mysql.LONGTEXT(), nullable=True),
    sa.Column('fecha_registro', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id_especie'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sesiones',
    sa.Column('id_sesion', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token_sesion', mysql.TEXT(), nullable=True),
    sa.Column('dispositivo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sistema_operativo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ip_usuario', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_inicio', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_expiracion', mysql.TIMESTAMP(), nullable=True),
    sa.Column('estado_sesion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='sesiones_ibfk_1'),
    sa.PrimaryKeyConstraint('id_sesion'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('liquenpedia',
    sa.Column('id_articulo', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('contenido', mysql.TEXT(), nullable=True),
    sa.Column('autor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('imagen_articulo', mysql.LONGTEXT(), nullable=True),
    sa.Column('estado_publicacion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_publicacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('fecha_actualizacion', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_articulo'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id_rol', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('nivel_acceso', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('zonas_ambientales',
    sa.Column('id_zona', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_zona', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('nivel_riesgo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('calidad_promedio_aire', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('fecha_actualizacion', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_zona'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mensaje', mysql.TEXT(), nullable=True),
    sa.Column('tipo_notificacion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado_notificacion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='notificaciones_ibfk_1'),
    sa.PrimaryKeyConstraint('id_notificacion'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('datasets',
    sa.Column('id_dataset', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_dataset', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('cantidad_imagenes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ruta_archivo', mysql.TEXT(), nullable=True),
    sa.Column('tipo_datos', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fuente_dataset', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado_dataset', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id_dataset'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('modelo_dataset',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_modelo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_dataset', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha_asociacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['id_dataset'], ['datasets.id_dataset'], name='modelo_dataset_ibfk_2'),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelos_ia.id_modelo'], name='modelo_dataset_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('apellido', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_documento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('numero_documento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('contrasena', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('foto_perfil', mysql.LONGTEXT(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_registro', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('ultimo_acceso', mysql.TIMESTAMP(), nullable=True),
    sa.Column('estado_cuenta', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_rol', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='usuarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('correo', 'usuarios', ['correo'], unique=True)
    op.create_table('procesamiento_ia',
    sa.Column('id_procesamiento', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_analisis', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tiempo_ejecucion', mysql.FLOAT(), nullable=True),
    sa.Column('porcentaje_precision', mysql.FLOAT(), nullable=True),
    sa.Column('precision_modelo', mysql.FLOAT(), nullable=True),
    sa.Column('cantidad_objetos_detectados', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resultado_segmentacion', mysql.TEXT(), nullable=True),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['id_analisis'], ['analisis.id_analisis'], name='procesamiento_ia_ibfk_1'),
    sa.PrimaryKeyConstraint('id_procesamiento'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ubicaciones',
    sa.Column('id_ubicacion', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('latitud', mysql.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitud', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('direccion', mysql.TEXT(), nullable=True),
    sa.Column('municipio', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('departamento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('altitud', mysql.FLOAT(), nullable=True),
    sa.Column('fecha_registro', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id_ubicacion'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analisis',
    sa.Column('id_analisis', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_modelo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_dataset', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_especie', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_ubicacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resultado_ia', mysql.TEXT(), nullable=True),
    sa.Column('porcentaje_confianza', mysql.FLOAT(), nullable=True),
    sa.Column('nivel_contaminacion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('calidad_aire', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado_liquen', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tiempo_procesamiento', mysql.FLOAT(), nullable=True),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('estado_validacion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('temperatura_ambiente', mysql.FLOAT(), nullable=True),
    sa.Column('humedad_relativa', mysql.FLOAT(), nullable=True),
    sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['id_dataset'], ['datasets.id_dataset'], name='analisis_ibfk_3'),
    sa.ForeignKeyConstraint(['id_especie'], ['especies_liquenes.id_especie'], name='analisis_ibfk_4'),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelos_ia.id_modelo'], name='analisis_ibfk_2'),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicaciones.id_ubicacion'], name='analisis_ibfk_5'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='analisis_ibfk_1'),
    sa.PrimaryKeyConstraint('id_analisis'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

